#!/usr/bin/env bash
# redink installer — writes a launcher at ~/.local/bin/redink pointing at this clone.
# Edits to src/redink/ take effect immediately. No reinstall needed.

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
LAUNCHER_DIR="${HOME}/.local/bin"
LAUNCHER="${LAUNCHER_DIR}/redink"

mkdir -p "${LAUNCHER_DIR}"

cat > "${LAUNCHER}" <<EOF
#!/usr/bin/env bash
# auto-generated by redink install.sh
exec python3 -c "import sys; sys.path.insert(0, '${REPO_ROOT}/src'); from redink.cli import main; sys.exit(main())" "\$@"
EOF

chmod +x "${LAUNCHER}"

echo "✓ Installed redink → ${LAUNCHER}"
echo ""

if ! command -v redink >/dev/null 2>&1; then
  echo "⚠ ${LAUNCHER_DIR} is not on your PATH."
  echo "  Add this to your shell profile (~/.zshrc or ~/.bashrc):"
  echo ""
  echo "    export PATH=\"\$HOME/.local/bin:\$PATH\""
  echo ""
  echo "  Then reload your shell."
  echo ""
fi

echo "Try it:  redink version"
echo "         redink --help"
